import {
  Flame, Heart, Zap, BookOpen, Trophy, Medal, User, Gamepad2, Newspaper,
  TriangleAlert, ClipboardList, Handshake, Building2, OctagonX, CloudRain,
  DollarSign, Lightbulb, Bike, Shield, CheckCircle, Ban,
  School, Circle, Undo2, Redo2, Car, ArrowRight, Hash, Route, ArrowUpRight,
  Plus, Mountain, FolderArchive, Brain, Hospital, ChartNoAxesColumnDecreasing,
  Wrench, Eye, Search, Moon, Smartphone, Headphones, Map, Frown, Wind, Smile,
  ParkingCircle, Phone, Camera, FileText, Timer, Lock, Target, Award, Star,
  Pencil, ChartNoAxesColumnIncreasing, Settings, RefreshCw, Trash2, Rocket,
  Key, PartyPopper, EyeOff, Sparkles, Crown, CircleHelp, Info, X, Dumbbell,
  ShieldCheck, Scroll, ChevronDown, RotateCcw, ArrowLeft, Bell,
  MessageSquareText, List, Maximize2, Minus, GripHorizontal, Waypoints,
  StretchHorizontal, Sun, CircleDot, Compass, Trees, Check, ArrowUp,
  ArrowDown, ChevronUp, ChevronRight, AlertOctagon, Pill, Flag,
  Radio, Siren, Maximize, CornerUpRight, Sunset, Warehouse,
  Construction, Rabbit, Gauge, Cross, CircleAlert, ArrowLeftFromLine,
  ArrowRightFromLine,   Columns2, Frame, LayoutGrid, PersonStanding,
  Minus as Dash, Plus as CrossSign, AlertTriangle,
  Fuel, Video, HelpCircle, ThumbsUp, Clover,
  Award as Ribbon, Sun as Brightness, Cloud, CloudSun,
  Volume2, Pause, Play, SkipForward, SkipBack,
  HeartHandshake, ShieldAlert, Ambulance as AmbulanceCar,
  CircleOff, Heart as LifeHeart,
  Sparkle, Gamepad, Cat, Laugh, SmilePlus,
} from 'lucide-react'

const EMOJI_MAP = {
  '🔥': Flame,
  '❤️': Heart,
  '⚡': Zap,
  '📚': BookOpen,
  '🏆': Trophy,
  '🏅': Medal,
  '👤': User,
  '🎮': Gamepad2,
  '📰': Newspaper,
  '🚦': TriangleAlert,
  '📋': ClipboardList,
  '🤝': Handshake,
  '🌆': Building2,
  '🛑': OctagonX,
  '🌧️': CloudRain,
  '💸': DollarSign,
  '💡': Lightbulb,
  '🏍️': Bike,
  '🦺': Shield,
  '🟢': CheckCircle,
  '🟡': Circle,
  '🔴': Circle,
  '⛔': Ban,
  '⚠️': TriangleAlert,
  '🚶': PersonStanding,
  '🏫': School,
  '🔵': Circle,
  '🚲': Bike,
  '🚫': Ban,
  '↩️': ArrowLeftFromLine,
  '↪️': ArrowRightFromLine,
  '🚘': Car,
  '🔢': Hash,
  '5️⃣': Hash,
  '➡️': ArrowRight,
  '〽️': Route,
  '↗️': ArrowUpRight,
  '✛': Plus,
  '🚸': PersonStanding,
  '🦌': Rabbit,
  '🚧': Construction,
  '⛰️': Mountain,
  '🗂️': FolderArchive,
  '🪧': MessageSquareText,
  '🧠': Brain,
  '🚑': AmbulanceCar,
  '🏎️': Gauge,
  '🏙️': Building2,
  '🛣️': Route,
  '📉': ChartNoAxesColumnDecreasing,
  '🚗': Car,
  '🪞': Columns2,
  '🔧': Wrench,
  '👀': Eye,
  '🔍': Search,
  '🌙': Moon,
  '📱': Smartphone,
  '🎧': Headphones,
  '🗺️': Map,
  '😴': Moon,
  '😤': Frown,
  '💨': Wind,
  '😌': Smile,
  '😠': Frown,
  '🅿️': ParkingCircle,
  '🏔️': Mountain,
  '🤕': Hospital,
  '📞': Phone,
  '📸': Camera,
  '📄': FileText,
  '🌑': Moon,
  '⏱': Timer,
  '🔒': Lock,
  '🎯': Target,
  '🎖️': Award,
  '🌟': Star,
  '✏️': Pencil,
  '✅': Check,
  '📊': ChartNoAxesColumnIncreasing,
  '⚙️': Settings,
  '🔄': RefreshCw,
  '🗑️': Trash2,
  '⭐': Star,
  '🚀': Rocket,
  '☸': Compass,
  '🔑': Key,
  '🎉': PartyPopper,
  '🙈': EyeOff,
  '👁️': Eye,
  '✨': Sparkles,
  '👑': Crown,
  '❓': CircleHelp,
  'ℹ️': Info,
  '✗': X,
  '✕': X,
  '✓': Check,
  '💪': Dumbbell,
  '🔎': Search,
  '😊': Smile,
  '😅': Laugh,
  '⤴️': CornerUpRight,
  '🛡️': Shield,
  '🚨': Siren,
  '💥': Zap,
  '🚓': Car,
  '🐢': Circle,
  '👿': Frown,
  '⚽': Circle,
  '❌': X,
  '🚳': Ban,
  '👮': ShieldCheck,
  '📜': Scroll,
  '🔽': ChevronDown,
  '🥇': Medal,
  '🥈': Medal,
  '🥉': Medal,
  '↺': RotateCcw,
  '←': ArrowLeft,
  '→': ArrowRight,
  '🔔': Bell,
  '🚶‍♂️': PersonStanding,
}

const COLORED = {
  '🟢': '#00e676',
  '🟡': '#ffd740',
  '🔴': '#ff5252',
  '🔵': '#448aff',
}

export function Icon({ icon, size = 16, className, style, strokeWidth, color }) {
  const LucideIcon = EMOJI_MAP[icon]
  if (!LucideIcon) {
    return <span style={{ fontSize: size, ...style }} className={className}>{icon}</span>
  }
  const iconColor = color || COLORED[icon] || 'currentColor'
  return (
    <LucideIcon
      size={size}
      className={className}
      style={style}
      color={iconColor}
      strokeWidth={strokeWidth}
    />
  )
}
